test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,9 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npx lint-staged
+
+if [$? = 0]; then
+  echo "Lint is successful and no errors found"
+else
+  echo "Lint is unsuccessful and errors found"
+fi
